---
- name: Automating everything about apache2 sites
  hosts: localhost
  become: yes
  gather_facts: false
  vars_prompt:
    - name: "file_path"
      prompt: "Path for the domains name file :"
      private: false
  tasks:
    - name: Check if apache2 is installed
      apt:
        name: apache2
        state: present
    - name: Send a domains_name file to the givent host
      copy:
        src: {{ file_path }}
        dest: /tmp/domains_name.txt
    - name: Sead the donamains_name file
      command: cat /tmp/domains_names.txt
      register: names_output
